name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-unknown-linux-gnu

      - uses: swatinem/rust-cache@v2
        with:
          shared-key: "nightly-cache"

      - run: cargo +nightly fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo check
